### PR TITLE
Remove RFC1123 from toleration keys

### LINKED ISSUE #389: BUG: toleration_keys lowercase RFC1123
Currently a taint of `CriticalAddonsOnly` can't be tolerated due to this constraint:

```
╷
│ Error: Invalid Attribute Value Match
│
│   with flux_bootstrap_git.this,
│   on flux.tf line 27, in resource "flux_bootstrap_git" "this":
│   27:   toleration_keys        = ["CriticalAddonsOnly"]
│
│ Attribute toleration_keys[Value("CriticalAddonsOnly")] a lowercase RFC 1123 label must consist of lower case alphanumeric characters
│ or '-', and must start and end with an alphanumeric character, got: CriticalAddonsOnly
```

/label bug

### PR DESCRIPTION
**Pull request by cdenneen**
Fixes #389

### CODE REVIEW

**Comment by cdenneen** [comment]
@phillebaba can you review?

**Comment by cdenneen** [comment]
@phillebaba I just tried to build this locally for testing and it's complaining about:

```
╷
│ Error: Unsupported argument
│
│   on flux.tf line 2, in provider "flux":
│    2:   host                   = module.eks.cluster_endpoint
│
│ An argument named "host" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on flux.tf line 3, in provider "flux":
│    3:   cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
│
│ An argument named "cluster_ca_certificate" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on flux.tf line 4, in provider "flux":
│    4:   token                  = data.aws_eks_cluster_auth.default.token
│
│ An argument named "token" is not expected here.
╵
```

which it wasn't before. So I checked and looks like you made some changes so I re-configured flux as:
```hcl
provider "flux" {
  git = {
    url = "ssh://git@gitlab.example.com/${var.gitlab_project_path}/${var.repository_name}.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.main.private_key_pem
    }
  }
}
```

but even with that configured it tells me it's not configured?

```
╷
│ Error: Unconfigured Clients
│
│   with flux_bootstrap_git.this,
│   on flux.tf line 23, in resource "flux_bootstrap_git" "this":
│   23: resource "flux_bootstrap_git" "this" {
│
│ Expected configured provider clients.
```

**Comment by phillebaba** [comment]
Yes so we just merged a breaking configuration change to the provider. Hopefully the first and only. I have written a guide describing the changes required.
https://github.com/fluxcd/terraform-provider-flux/blob/main/docs/guides/breaking-provider-configuration.md

**Comment by cdenneen** [comment]
ok so I added:

```hcl
provider "flux" {
  kubernetes = {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    token                  = data.aws_eks_cluster_auth.default.token
  }
  git        = {
    url = "ssh://git@gitlab.example.com/${var.gitlab_project_path}/${var.repository_name}.git"
    ssh = {
      username    = "git"
      private_key = tls_private_key.main.private_key_pem
    }
  }
}
```

this helped it actually start to apply but now the pods are Running (as opposed to Pending with the toleration change) but almost immediately failed with no other error:

```
flux_bootstrap_git.this: Creating...
flux_bootstrap_git.this: Still creating... [10s elapsed]
╷
│ Error: Bootstrap run error
│
│   with flux_bootstrap_git.this,
│   on flux.tf line 28, in resource "flux_bootstrap_git" "this":
│   28: resource "flux_bootstrap_git" "this" {
│
│ bootstrap failed with 1 health check failure(s)
╵
```

**Comment by cdenneen** [comment]
```
$ k -n flux-system get po
NAME                                           READY   STATUS    RESTARTS   AGE
helm-controller-5777f5644b-zfl78               1/1     Running   0          2m6s
image-automation-controller-57b776c9c6-fk8hm   1/1     Running   0          2m6s
image-reflector-controller-596b79d595-rbjws    1/1     Running   0          2m6s
kustomize-controller-746894b5c8-287rm          1/1     Running   0          2m6s
notification-controller-58cfb96d48-qfr5f       1/1     Running   0          2m6s
source-controller-5577b68c57-2z48d             1/1     Running   0          2m6s
$ k -n flux-system get svc
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
notification-controller   ClusterIP   172.20.112.106   <none>        80/TCP    85m
source-controller         ClusterIP   172.20.65.44     <none>        80/TCP    85m
webhook-receiver          ClusterIP   172.20.139.185   <none>        80/TCP    85m
$ k -n flux-system get ep
NAME                      ENDPOINTS            AGE
notification-controller   10.224.18.61:9090    85m
source-controller         10.224.18.112:9090   85m
webhook-receiver          10.224.18.61:9292    85m
```

**Comment by cdenneen** [comment]
> In your case you are missing the Kubernetes attribute block in the provider.
Wish it actually said which provider it needed. Thanks!

**Comment by phillebaba** [comment]
Could you run this from a clean state? It feels  like this may just be an issue with the provider waiting too long for Pods to reach a healthy state.

**Comment by cdenneen** [comment]
I re-ran the apply and it `Creation completion` so it is good now.
Obviously my current config is only based on HEAD with my toleration fix...
once you have the update to the PR and can merge... create release I can go
back to upstream registry
Right now I'm stuck using local path `~/.terraform.d/plugins`

**Comment by phillebaba** [comment]
Closing as this has been fixed.

**Pull request closed without merging**
