### PR TITLE
Update Go to v1.17

### PR DESCRIPTION
**Pull request by relu**

### CODE REVIEW

**Review by phillebaba — APPROVED** [review]
LGTM

**Comment by stefanprodan** [comment]
@relu please mark all the Go v1.17 PRs as blocked, we don't want these merged randomly.

**Comment by phillebaba** [comment]
OK sorry was not aware that we are waiting with the merging

**Review by stefanprodan — CHANGES_REQUESTED** [review]
DO NOT MERGE

**Comment by stefanprodan** [comment]
@phillebaba changes like this should follow the release procedure described here: https://github.com/fluxcd/flux2/blob/main/docs/internal/release.md, this means pkg -> controllers -> cli -> tf

**Review by stefanprodan — APPROVED** [review]

**Comment by relu** [comment]
Oops, I ran `make test` locally but I see now it's not actually running the suite of tests. I'll look into the failures.

**Comment by stefanprodan** [comment]
@phillebaba can you help us understand why is this failing?

**Comment by relu** [comment]
Should be fixed now. The version constraint was wrong in the `example/install` module used by the CI. I just changed that to point to the static version we use on `make install`.

**Comment by stefanprodan** [comment]
> The version constraint was wrong

How come it worked until now?

**Comment by relu** [comment]
I don't have an answer for that but it likely has to do with the terraform version we've used.

**Comment by relu** [comment]
Following up with some details here. There were two issues:
1. The GOOS and GOARCH environment variables were not set and this led to an invalid installation path.
2. The version constraint was not matching since it was targeting versions equal to or over 0.0.13, while the installed provider was set to 0.0.0-dev.

I think the way it is now is correct, I think terraform in the most recent versions became a bit more strict in terms of local filesystem plugin discovery.

**Comment by phillebaba** [comment]
@relu seems like you are correct regarding the version constraints and changes to where Terraform looks for local providers. The examples version should have been 0.0.0-dev, not really sure why I set it to anything else.

**Pull request merged**
