### PR TITLE
Skip git manifests deletion

### PR DESCRIPTION
**Pull request by invin12**
Optionally skip manifests deletion from git repository on terraform destroy

### CODE REVIEW

**Review by swade1987 — APPROVED** [review]

**Comment by swade1987** [comment]
@invin12 you need to run `make docs` and submit the changes.

**Comment by swade1987** [comment]
Thanks, @invin12. Would you be okay with waiting until I get @stefanprodan to approve and merge #615, as it's a big refactor/simplification of the documentation? Once we have that merged, we can merge your changes over the top.

**Comment by invin12** [comment]
> Thanks, @invin12. Would you be okay with waiting until I get @stefanprodan to approve and merge #615, as it's a big refactor/simplification of the documentation? Once we have that merged, we can merge your changes over the top.

Of course I don't mind, thanks!

**Comment by swade1987** [comment]
@invin12 could you please pull `main` onto your branch and run `make docs` please.

I would also recommend during `pre-commit install`

**Comment by invin12** [comment]
> @invin12 could you please do the following:
> 
> 1. Rebase your branch against the main branch
> 2. Run `pre-commit install`
> 3. Run `make docs`
> 4. Commit all changes.
> 5. Squash everything into a single commit.
> 
> Many thanks in advance.

All done

**Comment by swade1987** [comment]
@invin12, can I propose we reverse your logic and return if the user chooses not to delete the manifests? This just means we don't have to have the whole thing wrapped in a massive `if` block.

**Comment by invin12** [comment]
> @invin12, can I propose we reverse your logic and return if the user chooses not to delete the manifests? This just means we don't have to have the whole thing wrapped in a massive `if` block.

Ok, logic is changed.

**Review by swade1987 — APPROVED** [review]

**Comment by swade1987** [comment]
We will need to wait for @stefanprodan to get back next week to approve and merge this @invin12

**Comment by swade1987** [comment]
Closing due to inactivity will be tracking via https://github.com/fluxcd/terraform-provider-flux/pull/650

**Pull request closed without merging**
