### PR TITLE
Ignore fields user guide

### PR DESCRIPTION
**Pull request by luisgj**
Recently we got an issue where the `kubectl` provider along with the `fluxcd` provider end up always performing an update-in-place. The fix is rather easy so I thought a user guide may be useful for people running into this issue.

Signed-off-by: Luis Gabriel [guayabas@hey.com](mailto:guayabas@hey.com)

### CODE REVIEW

**Comment by stefanprodan** [comment]
Flux sets labels on each object after bootstrap, why do we tell people to ignore `metadata.annotations` instead of `metadata.labels`?

**Comment by luisgj** [comment]
@stefanprodan did a yaml diff and for my specific case, I saw no new labels being added, just annotations and after testing this, it seems no new labels where being dtected. But glad to edit the example to add labels if you deem it useful.

**Comment by darkowlzz** [comment]
Hi, I've been wondering about this and trying to reproduce this scenario. In my terraform plans, I do see in-place updates for `yaml_incluster`. Looking at the corresponding object in the cluster, for example source-controller deployment, I see annotation like:

```yaml
  annotations:
    deployment.kubernetes.io/revision: "21"
```

which sure aren't in the terraform configuration.
For such things, I guess using `ignore_fields` to ignore the annotations is okay, unless the flux manifest starts adding annotations in the future. I believe overwriting these annotations with terraform is harmless as we ensure our attributes are present and any other attributes added by K8s itself are automatically added if removed by terraform. I'm not sure if we need to officially document ways to ignore such drifts or rather document what they mean with proper reasoning behind them.
But I don't think we should be ignoring spec. Differences in spec are important to be tracked and need to be reconciled whenever there's a drift detected.

**Comment by luisgj** [comment]
Hi @darkowlzz What k8s provider are you using? Most likely a cloud provider will have mutating webhooks. I had this problem on EKS.

**Comment by darkowlzz** [comment]
> What k8s provider are you using? Most likely a cloud provider will have mutating webhooks. I had this problem on EKS.

I'm using a self-hosted k0s cluster.
If the whole spec is ignored using the `ignore_fields` kubectl argument, will this provider actually work at all? When there's a new flux version, wouldn't the spec be ignored and everything will become no-op?

As per https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest#ignore-manifest-fields, individual fields can be ignored. Can we do with ignoring only the specific fields in spec and annotation that are mutated by the mutating webhook?

**Comment by phillebaba** [comment]
@darkowlzz I do not think the provider will work if the whole spec is ignored, which was why i was hesitant in the first place. I would be more interested in knowing what mutation is causing issues for the provider.

As far as I know EKS does not mutate anything applied to the cluster by default? Must be something else.

**Comment by luisgj** [comment]
I has the same inquiry at first. That's why I have already made those tests. The provider does work if you change the manifests like bumping the version or other actions. It will detect changes to the `parsed_yaml` and `yaml_body` properties so plan will work normal.

**Comment by darkowlzz** [comment]
`yaml_incluster` drift seems to be related to https://github.com/gavinbunney/terraform-provider-kubectl/issues/92 .
@luisgj can you share more about the changes done by the mutating webhook?

I did see the spec being updated when upgrading the flux provider version with spec ignored in `kubectl_manifest`. Not sure why it doesn't completely ignores the spec, but if that's the case, I'd assume it's not doing what it's supposed to do and ignoring spec may not do anything.

**Comment by stefanprodan** [comment]
We no longer depend on the `kubectl` provider, the `flux_bootstrap_git` uses Flux server-side apply.

**Pull request closed without merging**
