### PR TITLE
Add example for writing Flux manifests to local file system

### PR DESCRIPTION
**Pull request by DaemonDude23**
Adding an example of using the [`local_file` provisioner](https://registry.terraform.io/providers/hashicorp/local/latest) to render Flux install and Flux sync manifests locally.

Signed-off-by: Andrew Aadland <aa23@protonmail.com>

### CODE REVIEW

**Comment by chicken231** [comment]
@errordeveloper Here's that local_file PR we discussed earlier in the week.

**Comment by phillebaba** [comment]
Thanks for the contribution :rose: 

Is there any specific reason that we should add a guide which would help others? FYI if you want the example to show up in the registry page we would need to write a for this example.

**Comment by errordeveloper** [comment]
> FYI if you want the example to show up in the registry page we would need to write a [...] for this example.

@phillebaba is 'readme' the word you missed?

**Comment by phillebaba** [comment]
@errordeveloper thanks for catching this, I was pretty tired when typing this. What I meant to type was guide :p

Guides are generated from templates. The GitHub guide is a good example of how it may look.
https://github.com/fluxcd/terraform-provider-flux/blob/main/templates/guides/github.md.tmpl

Then you simply rung `make docs` to generate the README. All dependencies are managed by go and the makefile so no extra installation needed.

**Comment by chicken231** [comment]
Thanks, I was confused by the initial reply too.
I'll see about creating this README before the upcoming weekend is out.

**Pull request closed without merging**
