### PR TITLE
Adding bug report issue template

### PR DESCRIPTION
**Pull request by swade1987**
Add a bug report issue template to gain consistency in filing bug reports.

### CODE REVIEW

**Comment by swade1987** [comment]
@stefanprodan any chance we could get this reviewed, approved and merged please 🙏 I really think it will help future bug reports.

**Comment by stefanprodan** [comment]
Hey @swade1987 can you please squash the commits into a single one. Thanks

**Comment by swade1987** [comment]
> Hey @swade1987 can you please squash the commits into a single one. Thanks

All done @stefanprodan

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @swade1987 🥇

**Pull request merged**
