### PR TITLE
Update Makefile add install option

### PR DESCRIPTION
**Pull request by nlarzon**
Change the artifact name on make build from flux to
terraform-provider-flux

Signed-off-by: Niklas Larsson <nlarzon@gmail.com>

### CODE REVIEW

**Comment by nlarzon** [comment]
I hope changing the artifact name not will impact the release process.

**Comment by phillebaba** [comment]
The release is done with a separate pipeline, so it wont be affected by the name change.

Is the purpose of this to make the development process easier or is this for users who cant fetch the provider from the registry?

**Comment by nlarzon** [comment]
Yes, it is for the dev process u can do `make install` to get the provider built and placed in the plugins folder

**Comment by phillebaba** [comment]
Can we change this to install the binary locally in the directory? My worry is that using terraform.d in the users home directory has side effects which could cause you to use wrong binary by mistake in other projects.

**Comment by nlarzon** [comment]
It did not work as well as expected.

**Comment by phillebaba** [comment]
Ok, this is still an issue as we need a dev guide for how people should try things out locally. So if you come up with a solution please open a new PR.

**Pull request closed without merging**
